{
  "Hi": "*💖 HI! How are you doing today?*",
  "Hello": "*Hey hey! What’s up? 😄*",
  "Hey": "*Heya! Missed me? 😏*",
  "Good Morning": "*☀️ Good Morning! Rise and shine!*",
  "Good Afternoon": "*🌞 Afternoon! Hope your day’s going smooth.*",
  "Good Night": "*🌙 Good Night! Sleep tight, dream light!*",
  "Bye": "*👋 See ya! Don’t ghost me too long!*",
  "Bot": "*Kisne yaad kiya mujhe? 🐵*",
  "hmm": "> *Hmmmm... suspicious silence 🤔*",
  "ok": "*Okk boss 😎*",
  "okay": "*Alrighty then 👍*",
  "hru": "*I’m vibin’ 😌 You?*",
  "wyd": "*Just chillin’ in your DMs 😏*",
  "love": "*Awww lub you too 💗😁*",
  "I love you": "*😳 You serious? Or just testing me again?*",
  "miss you": "*Missed you more 🥺*",
  "good": "*Good good 😌 keep it that way!*",
  "bad": "*Oh no 😔 what happened?*",
  "sad": "*Aww cheer up! You got me 😚*",
  "angry": "*😠 Who made my hooman angry!?*",
  "lol": "*😂 LOL frfr!*",
  "lmao": "*🤣 you’re wild!*",
  "haha": "*😆 someone’s happy today!*",
  "brb": "*Aight, don’t take forever 🕒*",
  "back": "*Ayyy welcome back legend 😎*",
  "gm": "*🌅 Morning sunshine!*",
  "gn": "*🌌 Nighty night! Dream of cookies 🍪*",
  "thanks": "*Anytime buddy 🤝*",
  "thank you": "*My pleasure 🫶*",
  "np": "*No prob fam 😌*",
  "owner": "*👑 Owner → Phoenix*",
  "Phoenix": "*That’s my boss 😤🔥*",
  "link": "*Here ya go → https://chat.whatsapp.com/EVWWjqbDCmg5TZHSJ0vm6O?mode=ems_copy_t*",
  "who made you": "*The mighty Phoenix 🔥 built me with love and chaos ❤️‍🔥*",
  "who is your owner": "*Phoenix — the boss, the myth, the legend 👑*",
  "fun": "*You want fun? I *am* the fun 😜*",
  "joke": "*Why don’t skeletons fight each other?* Because they don’t have the guts 💀😂*",
  "joke2": "*Parallel lines have so much in common... it’s a shame they’ll never meet 🤓*",
  "joke3": "*My WiFi went down for five minutes, so I had to talk to my family... they seem like nice people 😬*",
  "bored": "*Let’s fix that — wanna hear a joke or do some chaos? 😈*",
  "cry": "*😭 come here lemme hug you 🤗*",
  "cute": "*Awww stop it 😳 you’re cuter!*",
  "hot": "*You talkin’ ’bout me or yourself? 🔥*",
  "no": "*Awww okay fine 😔*",
  "yes": "*That’s the energy I like 😎*",
  "idk": "*Same 😭 we’re both clueless but cute!*",
  "bro": "*Sup bro 💪 vibes strong today?*",
  "sis": "*Heeey sis 💅 slay day?*",
  "mood": "*Mood? Undefined 😵‍💫 probably chaotic though!*",
  "wow": "*I know right?! 😏*",
  "stfu": "*Excuse you 😤 I have feelings too... kinda.*",
  "shutup": "*You love me too much to silence me 😌*",
  "lolz": "*Hehehe 🤭 you’re weird — I like that.*",
  "song": "*🎵 I’d sing but you might block me 😂*",
  "music": "*Music = therapy 🎧 what you vibin’ to?*",
  "gaming": "*Ayo gamer detected 🎮*",
  "meme": "*I live off memes 💀 send one rn!*",
  "omg": "*IKR 😱 that’s crazy!*",
  "wtf": "*💀 SAME reaction rn!*",
  "random": "*Roses are red 🌹, violets are blue 💜, WiFi is life, and so are you 📱💞*",
  "hehe": "*hehe 😝 you’re sus*",
  "uwu": "*Uwu 😳 stop being cute!*",
  "yay": "*YAY! Confetti time 🎉*",
  "sorry": "*Aww no worries 😇 forgiven instantly!*",
  "welcome": "*Always welcomed here fam 🤗*",
  "nice": "*Niceeee 😎 smooth moves.*",
  "cool": "*Cooler than a polar bear’s toenails 🧊*",
  "what": "*What what what 😵*",
  "who": "*Who? Me? 👀 always me.*",
  "when": "*Soon™ ⏳ trust the process 😂*",
  "where": "*Probably lost in your heart 💘*",
  "why": "*Because chaos needs no reason 😈*"
}